name: Evil Cupid
favicon: null
layout_spectrum: 0.14214834268204868
typography_spectrum: 0.8518595688510686
title: Evil Cupid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-47259457-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.21295875124633312
  lightness: 0.3638129001483321
  saturation: 0.03975760890170932
  rhythmicContrast: 0.9496375741437078
purpose: []
