name: Evil Cupid
favicon: null
layout_spectrum: 0.74315
typography_spectrum: 0.20912
title: Evil Cupid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-47259457-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf0f1'
    - '#32b4e4'
    - '#e8443b'
    - '#000000'
    - '#00ff00'
  brandStrength: 0.21295875124633312
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
